import { LibraryModel } from "../../Search.types";

export const MockedListData: LibraryModel[] = [
  {
    dependent_repos_count: 109038,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "The most popular front-end framework for developing responsive, mobile first projects on the web.",
    forks: 76463,
    homepage: "https://getbootstrap.com/",
    keywords: [
      "css",
      "js",
      "less",
      "mobile-first",
      "responsive",
      "front-end",
      "framework",
      "web",
      "bootstrap",
      "css-framework",
      "html",
      "javascript",
      "sass",
      "scss",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v4.6.1",
    latest_release_published_at: "2021-10-28T14:45:21.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "bootstrap",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 22,
    repository_license: "MIT",
    repository_url: "https://github.com/twbs/bootstrap.git",
    stars: 156337,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 37891,
    dependents_count: 0,
    deprecation_reason: null,
    description: "Font Awesome",
    forks: 12002,
    homepage: "http://fontawesome.io",
    keywords: [
      "css",
      "font",
      "fontawesome",
      "icons",
      "svg-icons",
      "svg-sprites",
      "webfont",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "6.1.1",
    latest_release_published_at: "2022-03-22T15:24:29.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: true,
    licenses: '["OFL-1.1", "MIT", "CC-BY-3.0"]',
    name: "Font-Awesome",
    normalized_licenses: ["MulanPSL-1.0"],
    package_manager_url: null,
    platform: "Bower",
    rank: 21,
    repository_license: "Other",
    repository_url: "https://github.com/FortAwesome/Font-Awesome.git",
    stars: 69021,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 25391,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "Parse, validate, manipulate, and display dates in javascript.",
    forks: 7041,
    homepage: "momentjs.com",
    keywords: [
      "moment",
      "date",
      "time",
      "parse",
      "format",
      "validate",
      "i18n",
      "l10n",
      "ender",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "2.29.2",
    latest_release_published_at: "2022-04-03T13:17:32.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "moment",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 21,
    repository_license: "MIT",
    repository_url: "https://github.com/moment/moment.git",
    stars: 46381,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 7671,
    dependents_count: 0,
    deprecation_reason: null,
    description: "Font Awesome",
    forks: 12002,
    homepage: "http://fontawesome.io",
    keywords: [
      "css",
      "font",
      "fontawesome",
      "icons",
      "svg-icons",
      "svg-sprites",
      "webfont",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "6.1.1",
    latest_release_published_at: "2022-03-22T15:24:29.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: true,
    licenses: '["OFL-1.1", "MIT", "CC-BY-3.0"]',
    name: "fontawesome",
    normalized_licenses: ["MulanPSL-1.0"],
    package_manager_url: null,
    platform: "Bower",
    rank: 20,
    repository_license: "Other",
    repository_url: "https://github.com/FortAwesome/Font-Awesome.git",
    stars: 69021,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 3658,
    dependents_count: 0,
    deprecation_reason: null,
    description: "Simple HTML5 Charts using the canvas element",
    forks: 11415,
    homepage: "https://github.com/chartjs/Chart.js",
    keywords: [
      "canvas",
      "chart",
      "graph",
      "hacktoberfest",
      "html5",
      "html5-charts",
      "javascript",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v3.7.1",
    latest_release_published_at: "2022-02-12T14:48:34.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "Chart.js",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 20,
    repository_license: "MIT",
    repository_url: "https://github.com/nnnick/Chart.js.git",
    stars: 56588,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 22436,
    dependents_count: 0,
    deprecation_reason: null,
    description: "Advanced HTML5 hybrid mobile app development framework.",
    forks: 13647,
    homepage: "https://github.com/driftyco/ionic",
    keywords: [
      "mobile",
      "html5",
      "ionic",
      "cordova",
      "phonegap",
      "trigger",
      "triggerio",
      "angularjs",
      "angular",
      "capacitor",
      "framework",
      "frontend",
      "ios",
      "javascript",
      "material-design",
      "pwa",
      "react",
      "stencil",
      "stenciljs",
      "typescript",
      "vue",
      "web",
      "webcomponents",
    ],
    language: "TypeScript",
    latest_download_url: null,
    latest_release_number: "v6.0.14",
    latest_release_published_at: "2022-03-30T13:24:42.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "ionic",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 20,
    repository_license: "Other",
    repository_url: "https://github.com/driftyco/ionic.git",
    stars: 46678,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 2153,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "Parse, validate, manipulate, and display dates in javascript.",
    forks: 7041,
    homepage: "momentjs.com",
    keywords: [
      "moment",
      "date",
      "time",
      "parse",
      "format",
      "validate",
      "i18n",
      "l10n",
      "ender",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "2.29.2",
    latest_release_published_at: "2022-04-03T13:17:32.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "momentjs",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 20,
    repository_license: "MIT",
    repository_url: "https://github.com/moment/moment.git",
    stars: 46381,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 10718,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "Give your JS App some Backbone with Models, Views, Collections, and Events",
    forks: 5602,
    homepage: "http://backbonejs.org",
    keywords: [
      "model",
      "view",
      "controller",
      "router",
      "server",
      "client",
      "browser",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "1.4.1",
    latest_release_published_at: "2022-02-26T00:32:24.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: null,
    name: "backbone",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 20,
    repository_license: "MIT",
    repository_url: "https://github.com/jashkenas/backbone.git",
    stars: 27867,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 7997,
    dependents_count: 0,
    deprecation_reason: null,
    description: "Test spies, stubs and mocks for JavaScript.",
    forks: 785,
    homepage: "https://sinonjs.org/",
    keywords: [
      "javascript",
      "sinon",
      "stub",
      "stubs",
      "tdd",
      "test-driven-development",
      "test-spies",
      "unit-testing",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v13.0.0",
    latest_release_published_at: "2022-01-28T13:00:21.000Z",
    latest_stable_release_number: "v13.0.0",
    latest_stable_release_published_at: "2022-01-28T13:00:21.000Z",
    license_normalized: false,
    licenses: null,
    name: "sinon",
    normalized_licenses: ["Other"],
    package_manager_url: null,
    platform: "Bower",
    rank: 20,
    repository_license: "Other",
    repository_url: "https://github.com/cjohansen/Sinon.JS.git",
    stars: 8873,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 1074,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "🖖 Vue.js is a progressive, incrementally-adoptable JavaScript framework for building UI on the web.",
    forks: 31707,
    homepage: "http://vuejs.org",
    keywords: ["framework", "frontend", "javascript", "vue"],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v2.6.14",
    latest_release_published_at: "2021-06-07T09:55:29.000Z",
    latest_stable_release_number: "v2.6.14",
    latest_stable_release_published_at: "2021-06-07T09:55:29.000Z",
    license_normalized: false,
    licenses: null,
    name: "vue",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/vuejs/vue.git",
    stars: 194194,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 9982,
    dependents_count: 0,
    deprecation_reason: null,
    description: "A JavaScript visualization library for HTML and SVG.",
    forks: 23040,
    homepage: "https://d3js.org",
    keywords: [
      "dom",
      "w3c",
      "visualization",
      "svg",
      "animation",
      "canvas",
      "chart",
      "charts",
      "data-visualization",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v7.4.3",
    latest_release_published_at: "2022-04-07T18:14:00.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "BSD-3-Clause",
    name: "d3",
    normalized_licenses: ["BSD-3-Clause"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "ISC",
    repository_url: "https://github.com/mbostock-bower/d3-bower.git",
    stars: 100879,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 643,
    dependents_count: 0,
    deprecation_reason: null,
    description: "Simple HTML5 Charts using the canvas element",
    forks: 11415,
    homepage: "https://github.com/chartjs/Chart.js",
    keywords: [
      "canvas",
      "chart",
      "graph",
      "hacktoberfest",
      "html5",
      "html5-charts",
      "javascript",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v3.7.1",
    latest_release_published_at: "2022-02-12T14:48:34.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "chartjs",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/nnnick/Chart.js.git",
    stars: 56588,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 117463,
    dependents_count: 0,
    deprecation_reason: null,
    description: "Distribution repo for jQuery Core releases",
    forks: 20380,
    homepage: "https://jquery.com",
    keywords: ["jquery", "javascript", "browser", "library"],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "3.6.0",
    latest_release_published_at: "2021-03-02T17:08:15.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: null,
    name: "jQuery",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/jquery/jquery.git",
    stars: 56080,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 41110,
    dependents_count: 0,
    deprecation_reason: null,
    description: "jQuery JavaScript Library",
    forks: 20380,
    homepage: "https://jquery.com",
    keywords: ["jquery"],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "3.6.0",
    latest_release_published_at: "2021-03-02T17:08:15.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: null,
    name: "Jquery",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/jquery/jquery.git",
    stars: 56080,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 24347,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "A modern JavaScript utility library delivering modularity, performance, \u0026 extras.",
    forks: 6388,
    homepage: "https://lodash.com/",
    keywords: ["javascript", "lodash", "modules", "utilities"],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "4.17.21",
    latest_release_published_at: "2021-02-20T15:33:48.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: null,
    name: "lodash",
    normalized_licenses: ["Other"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "Other",
    repository_url: "https://github.com/lodash/lodash.git",
    stars: 52658,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 3747,
    dependents_count: 0,
    deprecation_reason: null,
    description: "A modern alternative to CSS resets",
    forks: 10600,
    homepage: "http://necolas.github.io/normalize.css/",
    keywords: ["css", "css-reset", "normalize-css"],
    language: "CSS",
    latest_download_url: null,
    latest_release_number: "8.0.1",
    latest_release_published_at: "2018-11-05T02:30:06.000Z",
    latest_stable_release_number: "8.0.1",
    latest_stable_release_published_at: "2018-11-05T02:30:06.000Z",
    license_normalized: false,
    licenses: "MIT",
    name: "normalize.css",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/necolas/normalize.css.git",
    stars: 46963,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 6275,
    dependents_count: 0,
    deprecation_reason: null,
    description: "A modern alternative to CSS resets",
    forks: 10600,
    homepage: "http://necolas.github.io/normalize.css/",
    keywords: ["css", "css-reset", "normalize-css"],
    language: "CSS",
    latest_download_url: null,
    latest_release_number: "8.0.1",
    latest_release_published_at: "2018-11-05T02:30:06.000Z",
    latest_stable_release_number: "8.0.1",
    latest_stable_release_published_at: "2018-11-05T02:30:06.000Z",
    license_normalized: false,
    licenses: "MIT",
    name: "normalize-css",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/necolas/normalize.css.git",
    stars: 46963,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 2505,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      " :leaves: JavaScript library for mobile-friendly interactive maps",
    forks: 5222,
    homepage: "https://leafletjs.com",
    keywords: ["gis", "map", "javascript", "leaflet", "maps"],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v1.8.0-beta.3",
    latest_release_published_at: "2022-04-04T15:51:22.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: null,
    name: "leaflet",
    normalized_licenses: ["BSD-2-Clause"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "BSD-2-Clause",
    repository_url: "https://github.com/Leaflet/Leaflet",
    stars: 33520,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 1113,
    dependents_count: 0,
    deprecation_reason: null,
    description: "Modern copy to clipboard. No Flash. Just 3kb",
    forks: 4043,
    homepage: "https://clipboardjs.com",
    keywords: ["clipboard", "copy", "cut", "javascript"],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v2.0.10",
    latest_release_published_at: "2022-02-02T15:13:00.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "clipboard",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/zenorocha/clipboard.js.git",
    stars: 31954,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 22349,
    dependents_count: 0,
    deprecation_reason: null,
    description: "JavaScript's utility _ belt",
    forks: 5627,
    homepage: "https://underscorejs.org",
    keywords: ["util", "functional", "server", "client", "browser"],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "1.13.2",
    latest_release_published_at: "2021-12-16T10:21:31.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: null,
    name: "underscore",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/jashkenas/underscore.git",
    stars: 26375,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 4306,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "Select2 is a jQuery based replacement for select boxes. It supports searching, remote data sets, and infinite scrolling of results.",
    forks: 6297,
    homepage: "https://select2.org/",
    keywords: [
      "select",
      "autocomplete",
      "typeahead",
      "dropdown",
      "multiselect",
      "tag",
      "tagging",
      "javascript",
      "jquery",
      "select2",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "4.1.0-rc.0",
    latest_release_published_at: "2021-01-23T04:36:25.000Z",
    latest_stable_release_number: "4.0.13",
    latest_stable_release_published_at: "2020-01-28T05:01:22.000Z",
    license_normalized: false,
    licenses: "MIT",
    name: "select2",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/ivaynberg/select2.git",
    stars: 25253,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 11843,
    dependents_count: 0,
    deprecation_reason: null,
    description: "simple, flexible, fun test framework",
    forks: 2935,
    homepage: "https://mochajs.org",
    keywords: [
      "mocha",
      "test",
      "bdd",
      "tdd",
      "tap",
      "browser",
      "javascript",
      "mochajs",
      "node",
      "nodejs",
      "test-framework",
      "testing",
      "testing-tools",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v9.2.1",
    latest_release_published_at: "2022-02-19T09:47:06.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "mocha",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/mochajs/mocha.git",
    stars: 21229,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 38094,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "The de-facto solution to flexible routing with nested views in AngularJS",
    forks: 3141,
    homepage: "http://ui-router.github.io/",
    keywords: [
      "angularjs",
      "javascript",
      "router",
      "routing",
      "state-machine",
      "state-tree",
      "typescript",
      "ui-router",
    ],
    language: "TypeScript",
    latest_download_url: null,
    latest_release_number: "1.0.30",
    latest_release_published_at: "2021-12-01T02:49:40.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "angular-ui-router",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/angular-ui/angular-ui-router-bower.git",
    stars: 13729,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 952,
    dependents_count: 0,
    deprecation_reason: null,
    description: "Lightweight, robust, elegant syntax highlighting.",
    forks: 1188,
    homepage: "https://prismjs.com",
    keywords: ["prism", "highlight"],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v1.27.0",
    latest_release_published_at: "2022-02-17T21:38:46.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: null,
    name: "prism",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/PrismJS/prism",
    stars: 10142,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 12040,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "BDD/TDD assertion library for node.js and the browser. Test framework agnostic.",
    forks: 688,
    homepage: "https://chaijs.github.io",
    keywords: [
      "test",
      "assertion",
      "assert",
      "testing",
      "chai",
      "assertions",
      "bdd",
      "javascript",
      "tdd",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v4.3.6",
    latest_release_published_at: "2022-01-26T13:10:42.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "chai",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/chaijs/chai.git",
    stars: 7522,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 16448,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "ECMAScript 5 compatibility shims for legacy JavaScript engines",
    forks: 950,
    homepage: "https://github.com/es-shims/es5-shim",
    keywords: [
      "shim",
      "es5",
      "es5 shim",
      "javascript",
      "ecmascript",
      "polyfill",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v4.6.5",
    latest_release_published_at: "2022-02-09T22:48:45.000Z",
    latest_stable_release_number: "v4.6.5",
    latest_stable_release_published_at: "2022-02-09T22:48:45.000Z",
    license_normalized: false,
    licenses: "MIT",
    name: "es5-shim",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/es-shims/es5-shim.git",
    stars: 7070,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 14177,
    dependents_count: 0,
    deprecation_reason: null,
    description: "An easy-to-use JavaScript Unit Testing framework.",
    forks: 797,
    homepage: "https://qunitjs.com",
    keywords: ["javascript", "qunit", "testing"],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "2.17.2",
    latest_release_published_at: "2021-09-20T04:56:03.000Z",
    latest_stable_release_number: "2.17.2",
    latest_stable_release_published_at: "2021-09-20T04:56:03.000Z",
    license_normalized: false,
    licenses: null,
    name: "qunit",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 19,
    repository_license: "MIT",
    repository_url: "https://github.com/jquery/qunit",
    stars: 3934,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 62,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "The most popular front-end framework for developing responsive, mobile first projects on the web.",
    forks: 76463,
    homepage: "https://getbootstrap.com/",
    keywords: [
      "css",
      "js",
      "less",
      "mobile-first",
      "responsive",
      "front-end",
      "framework",
      "web",
      "bootstrap",
      "css-framework",
      "html",
      "javascript",
      "sass",
      "scss",
    ],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "v4.6.1",
    latest_release_published_at: "2021-10-28T14:45:21.000Z",
    latest_stable_release_number: null,
    latest_stable_release_published_at: null,
    license_normalized: false,
    licenses: "MIT",
    name: "twitter",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 18,
    repository_license: "MIT",
    repository_url: "https://github.com/twbs/bootstrap.git",
    stars: 156337,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 153,
    dependents_count: 0,
    deprecation_reason: null,
    description:
      "TypeScript is a superset of JavaScript that compiles to clean JavaScript output.",
    forks: 10346,
    homepage: "https://www.typescriptlang.org",
    keywords: ["javascript", "language", "typechecker", "typescript"],
    language: "TypeScript",
    latest_download_url: null,
    latest_release_number: "v4.6.2",
    latest_release_published_at: "2022-02-23T08:56:14.000Z",
    latest_stable_release_number: "v4.6.2",
    latest_stable_release_published_at: "2022-02-23T08:56:14.000Z",
    license_normalized: false,
    licenses: null,
    name: "typescript",
    normalized_licenses: ["Apache-2.0"],
    package_manager_url: null,
    platform: "Bower",
    rank: 18,
    repository_license: "Apache-2.0",
    repository_url: "https://github.com/Microsoft/TypeScript.git",
    stars: 79016,
    status: null,
    versions: [],
  },
  {
    dependent_repos_count: 1086,
    dependents_count: 0,
    deprecation_reason: null,
    description: "The HTML Presentation Framework",
    forks: 16071,
    homepage: "http://revealjs.com",
    keywords: ["presentations", "slides", "slideshow"],
    language: "JavaScript",
    latest_download_url: null,
    latest_release_number: "4.3.0",
    latest_release_published_at: "2022-02-28T09:03:16.000Z",
    latest_stable_release_number: "4.3.0",
    latest_stable_release_published_at: "2022-02-28T09:03:16.000Z",
    license_normalized: false,
    licenses: "MIT",
    name: "reveal.js",
    normalized_licenses: ["MIT"],
    package_manager_url: null,
    platform: "Bower",
    rank: 18,
    repository_license: "MIT",
    repository_url: "https://github.com/hakimel/reveal.js.git",
    stars: 58795,
    status: null,
    versions: [],
  },
];
